use_frameworks!

platform :ios, '10.0'

target 'HomeMoudle_Example' do
  pod 'HomeMoudle', :path => '../'

  target 'HomeMoudle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
